[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "xcm-procedural"
version = "0.9.28"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = "1.0.100"
Inflector = "0.11.4"
